### ISSUE TITLE
compile-xquery incompatible with Clojure 1.3

### ISSUE THREAD

**Issue by rplevy** [pjt/saxon#2]
If you load up the saxon library in 1.3 and evaluate
(saxon/compile-xquery "distinct-values(//element()/local-name())")
the result is:
NoSuchMethodError clojure.lang.Numbers.lt(II)Z  saxon/compile-xquery/fn--67 (saxon.clj:149)

This seems to be the case for all queries I've tried, and they work when I load the library in 1.2.

I've been looking for the source of incompatibility but so far I haven't found it.  Any idea on what causes this to fail in 1.3?

Thanks,
Rob

**Comment by rplevy** [comment]
Never mind, I found the compatibility branch.

**Comment by pjt** [comment]
Hi Robert,

I suspect this is just fallout from AOT compilation against 1.2. Perhaps it's time to rethink AOT-compiling the library in the first place; it's there so that the main method can be called from the Java commandline & I suspect that's a small use case. 

Either way, I should update the library for 1.3. (There's a branch, 1.3-compat, that has everything that's necessary.) I'll try to get that done this weekend. 

Perry

**Comment by pjt** [comment]
Just saw your second note. 

Is your issue solved? Are you using the lib from Clojars or building it yourself?

**Comment by rplevy** [comment]
Hi Perry, thanks, yup, the compat branch solves it.  I simply made a jar
with a specially named version in project.clj.  No changes to the code were
necessary.  I will use your latest upstream instead when that comes out.
On Nov 24, 2011 12:33 AM, "Perry Trolard" <
reply@reply.github.com>
wrote:

**Comment by tborg** [comment]
Hi there.

I was wondering if you still had plans to switch the master over to 1.3-compat? I like your library a lot; it's tremendously useful. It would be really nice if the jar I pulled off Clojars didn't break on 1.3, though.

**Comment by pjt** [comment]
Hi Robert,

At very long last, version 0.9.3 of clojure-saxon is up on Clojars & is compatible with Clojure 1.3 & 1.4. 

If you're still using the library, I'm curious to know if the particular version of Saxon that it wraps is important to you. There're more recent versions ("home edition" &c) that involve breaking changes, & I'd like to know how important upgrading to these would be. (I happen to no longer be a frequent XSLT user myself.)

Thanks,
Perry
